### ISSUE TITLE
Deluxe Settings not mentioned in readme, should be tweaked to include

### ISSUE THREAD

**Issue by shanmur2706** [hmxmilohax/beatles-rock-band-deluxe#15]
The documentation for tbrbdx, possibly other dx variants, needs a bit of work. I'll be happy to request the edit to the readme myself, but just felt it better to bring to attention.

I read the readme, but didn't know how to access those 'deluxe settings'. I wanted to change the highway is all lol, I don't like transparent ones. I installed it via pkg, installed from source with build bats, looked through the py code even. Only when I gave up looking and went to find milohax server to ask about it, I found that and the secret 2x star power press on wikihero for gh2dx instead.

If the main 'selling' point of a mod and the settings aren't specified how to access, I think that should be said. I understand that there's probably plenty enjoyers of the milohax mods that just know about them cause they're in the discord or something, but I'm just a casual player. I read the readme, but if it's not there or in some dedicated wiki, I generally wouldn't search this hard. I kinda knew from rb2/3dx what to look for in-game, but besides that wouldn't have known.

Anyway that's it. Just tweak the readme / documentation for this project and maybe the others, idk I haven't gone back and checked those.

**Comment by SCOTT0852** [comment]
Most of the readmes are admittedly forgotten besides RB3DX, but you're absolutely free to submit pull requests. I don't have TBRB set up currently so I can't check, but I believe it uses the same overshell system as other pre-RB3 Deluxe projects where you can open it from any menu by pressing select twice.

**Comment by jnackmclain** [comment]
That is a fair point but also these smaller dx projects are extremely early and are not very much supported, which leaves the documentation lacking as well for sure. Sorry about that.

**Comment by lunalawl** [comment]
tbrbdx is low-support, we haven't updated it among most other dx projects in a while. SELECT SELECT has been normalized among dx and rb2dx has text in the main menu that tells you how to open dx settings/ if you wanna edit the readme yourself feel free to open a pr
